### ISSUE TITLE
asm feature now stabilized

### ISSUE THREAD

**Issue by burrbull** [esp-rs/xtensa-lx#14]

**Comment by jessebraham** [comment]
Thanks for letting us know.

Will this be available in `1.58.0` or a later release? We build our compiler fork off stable releases, so unfortunately removing the `#![feature(asm)]` attribute results in build failures using the current version compiler (`1.57.0.2`). I'm able to build my modified version using `nightly`, however.

I have a PR ready to go for this, so I will submit it when we release our next build of the compiler.

**Comment by burrbull** [comment]
1.59.0

But anyway now building is broken on nightly. You need to delete feature and import it with `use core::arch::asm`

**Comment by burrbull** [comment]
`asm` is availible on beta now.
