### ISSUE TITLE
CriticalSectionSpinLockMutex shouldn't be available for targets w/o atomics support

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/xtensa-lx#16]
The ESP32S2 doesn't support atomics so we should either configure `CriticalSectionSpinLockMutex` away in that case or emulate it with just a critical section (which would be okay since ESP32S2 is single-core)

**Comment by jessebraham** [comment]
This has finally reared its head with the `1.60.0.1` release of the Xtensa fork of the Rust compiler. Building for the ESP32-S2 fails, see output here:  
https://gist.github.com/jessebraham/7f4cd81892ad2f5dc8d5decd4ff8a26f

**Comment by bjoernQ** [comment]
I guess "configure CriticalSectionSpinLockMutex away" (including the dependency) is the easiest solution here - we should just do it
