### ISSUE TITLE
Correct Xtensa critical sections

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/xtensa-lx#20]
The current critical sections are wrong, see https://github.com/esp-rs/esp-hal/issues/87 for more details, the TLDR is that we should not be disabling interrupts. On top of that, we should probably depend on `critical_section` crate to get the correct per chip implementations, instead of using `interrupt::free` everywhere.

**Comment by reitermarkus** [comment]
Is this closed by https://github.com/esp-rs/esp-hal/pull/151?

**Comment by MabezDev** [comment]
Yes, thanks for the ping @reitermarkus!
