### ISSUE TITLE
Should this package provide a critical section implementation?

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/xtensa-lx#24]
The [riscv](https://github.com/rust-embedded/riscv) package provides a default single-hart implementation behind a feature, as seen [here](https://github.com/rust-embedded/riscv/blob/ec99d035d62abaf2e6053c263e8a58a1186d1bbd/src/critical_section.rs).  
The [cortex-m](https://github.com/rust-embedded/cortex-m) package does the same [here](https://github.com/rust-embedded/cortex-m/blob/82fa94d2cd2829cc37111d247e913cecdad561ac/src/critical_section.rs).

Should we move our single-core (and dual-core?) Xtensa implementations into this package in the same manner? While there is no critical need for this change I think trying to keep in line with the other architecture support packages is probably not a bad idea.

**Comment by MabezDev** [comment]
I think our impls in esp-hal serve us better than something we could do here. Closing.
