### ISSUE TITLE
Support for LX2

### ISSUE THREAD

**Issue by Frostie314159** [esp-rs/xtensa-lx#36]
Are there any plans for supporting the LX2 microarch?

**Comment by igrr** [comment]
I don't think we have a manual for that one. Does it have any software-visible architectural differences compared to other Xtensa implementations?

**Comment by Frostie314159** [comment]
The only thing I have for that arch is, the firmware for the ar9271 nic https://github.com/qca/open-ath9k-htc-firmware I plan on writing a firmware for that nic.

**Comment by igrr** [comment]
Looking at the [config file](https://github.com/qca/open-ath9k-htc-firmware/blob/master/target_firmware/magpie_fw_dev/target/inc/xtensa/config/core-isa.h) of that core, I think the only thing that stands out, architecture wise, is that this is a big-endian configuration.

I am not sure there are any assumption about  endianness in the xtensa-lx crate or the Xtensa LLVM backend, for that matter. I don't think we've ever worked with a big-endian Xtensa core before, so it is probably something you'll have to try!

If it is of any help, you can add your specific core configuration to the QEMU emulator, likely making the initial development a bit simpler compared to doing it on real hardware.

**Comment by jessebraham** [comment]
We have no plans to support additional architecture at this time. We just finished removing LX106 support for various reasons.

I would suggest forking the repository. If you really feel that support for this arch should be included in this package, you're welcome to open a PR and include a `CODEOWNERS` file so it's clear who to contact with regards to maintenance.

**Comment by Frostie314159** [comment]
Thanks for the response, I'm going to close this, since it isn't planned.
