### ISSUE TITLE
Move packages to `esp-hal` repository

### ISSUE THREAD

**Issue by jessebraham** [esp-rs/xtensa-lx#40]
We're just going to keep forgetting about these packages, so I think it makes sense to move them in along with everything else. This is low-priority, I will take care of it when I get a chance. I'd also like to try and remove the git submodule first.

@MabezDev @bjoernQ please let me know if you have any objections to this, but I think it's the right call.

**Comment by bjoernQ** [comment]
I agree - t.b.h. I remember not touching them for some small changes because it's too cumbersome

**Comment by jessebraham** [comment]
- https://github.com/esp-rs/xtensa-lx/pull/41
- https://github.com/esp-rs/esp-hal/pull/1813
